### ISSUE TITLE
toggle showing of a test result

### ISSUE THREAD

**Issue by Zhami** [ded/sink-test#1]
Presently clicking on a test shows the test result. I thought it would be nice to click again to un-show. 

I forked your sink-test and made some changes. Alas, I'm not facile with git and GitHub and don't know how to send a Pull Request for just the one change I made. You can see it here: 
https://github.com/Zhami/sink-test/commit/f12365441561f98e133b4681d6e126a47800269e

**Comment by ded** [comment]
come to my repo, and click `pull request` at the top right-hand-side of the page

**Comment by Zhami** [comment]
(1) I click the "pull request" from my repo, not yours.
(2) I knew to do that, but didn't (and still don't) know how to send a pull request for a specific commit -- that's the problem -- the pull request as issued contains two commits -- see my comment to the request
These matters of GitHub aside, you guys have done ad do fantastic work -- thanks!!

**Comment by ded** [comment]
hmmm.... i think you can create another branch based on your one now. then `git checkout SHA123` to the previous state which it was good

**Comment by Zhami** [comment]
I finally figured out how to do this. The key is to maintain a branch in sync with your master, then create a new branch, and into that <code>git cherry-pick SHA1</code> to pull in specific commit(s). Then push the new branch. Which I have done, and have issued a pull request.

**Comment by ded** [comment]
Excellent. Ill have a look in the morning
